---
apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-import
  project: akshay
spec:
  version: v1
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
  repositoryOptions:
    name: caas-gke
    branch: main
    directoryPath: rafay-import/terraform/rafay-import
  contexts:
  - name: rctl-config
  agents:
  - name: ak-gke-eaas-agent
  versionState: active
