---
apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: gke-standard-cluster
  project: akshay
spec:
  version: v1
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
  repositoryOptions:
    name: caas-gke
    branch: main
    directoryPath: rafay-import-helm/terraform/gke
  contexts:
  - name: gcp-config
  - name: rctl-config
  agents:
  - name: ak-gke-eaas-agent
  versionState: active
