---
apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: gke-default-cluster
  project: akshay
spec:
  version: v1
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
  repositoryOptions:
    name: caas-gke
    branch: main
    directoryPath: default-cluster/terraform
  contexts:
  - name: gcp-config
  agents:
  - name: ak-gke-eaas-agent
  versionState: active
